# Site settings
title: Trent Nelson
email: contact@trent.me
description: > # this means to ignore newlines until "baseurl:"
    Trent Nelson's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trent.me"
twitter_username: trentnelson
github_username:  tpn

# Build settings
markdown: kramdown
highlighter: pygments
